# Generated by Django 6.0 on 2026-01-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField()),
                ('name', models.TextField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=512)),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('include_memorial', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'FuneralPackage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuneralType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, unique=True)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'FuneralType',
                'managed': False,
            },
        ),
    ]
