# Generated by Django 5.2.10 on 2026-01-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff',
            table='Staff',
        ),
    ]
