# Generated by Django 6.0 on 2026-01-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField()),
                ('place_of_death', models.TextField(max_length=128)),
                ('date_of_death', models.DateField()),
                ('cause_of_death', models.TextField(max_length=256)),
                ('death_certificate_number', models.TextField(max_length=64)),
                ('certified_by', models.TextField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Deceased',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'MaritalStatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField()),
                ('national_id', models.TextField(max_length=20, unique=True)),
                ('names', models.TextField(max_length=50)),
                ('last_names', models.TextField(max_length=100)),
                ('gender', models.TextField(max_length=1)),
                ('birthday', models.DateField()),
                ('birth_place', models.TextField(max_length=128)),
                ('occupation', models.TextField(max_length=64)),
                ('photo_url', models.TextField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField()),
                ('street', models.TextField(max_length=128)),
                ('township', models.TextField(max_length=128)),
                ('city', models.TextField(max_length=128)),
                ('province', models.TextField(max_length=128)),
                ('country_code', models.TextField(max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PersonAddress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField()),
                ('phone_number', models.TextField(max_length=128)),
                ('is_preferred_contact', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PersonPhoneNumber',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
            ],
            options={
                'db_table': 'PhoneNumberType',
                'managed': False,
            },
        ),
    ]
