# Generated by Django 6.0 on 2026-01-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField()),
                ('notes', models.TextField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Funeral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuneralStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, unique=True)),
                ('description', models.TextField(max_length=512)),
            ],
            options={
                'db_table': 'FuneralStatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuneralStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'FuneralStatusHistory',
                'managed': False,
            },
        ),
    ]
