# Generated by Django 5.2.10 on 2026-01-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funeral', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funeral',
            options={'managed': False, 'permissions': [('can_assign_funeral_package', 'Can assign a package to a funeral'), ('can_cancel_funeral', 'Can cancel a funeral'), ('can_close_funeral', 'Can close a funeral'), ('can_complete_funeral', 'Can mark a funeral as completed')]},
        ),
    ]
